language: c

env:
  - LUA='Lua 5.1'
  - LUA='Lua 5.2'
  - LUA='Lua 5.3'
  - LUA='LuaJIT 2.0'

branches:
  only:
    - master

before_install:
  - bash .travis_setup.sh

install:
  - sudo apt-get update -qq
  - sudo luarocks install luasec
  - sudo luarocks install luacheck
  - sudo luarocks install busted
  - sudo luarocks install dkjson
  - sudo luarocks install yaml
  - sudo luarocks install inifile

script:
  - luacheck .
  - busted spec

notifications:
  email:
    on_success: change
    on_failure: always